[package]
name = "abc335"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.5"
itertools = "0.10.5"
num = "0.4.0"
proptest = "1.0.0"
petgraph = "0.6.4"